[package]
name = "binary_utils"
version = "0.2.2"
authors = ["Bavfalcon9"]
edition = "2021"
include = ["src/**/*", "README.md"]

[dependencies]
byteorder = "1.4.3"
bin_macro = { path = "./bin_macro" }

[features]
